locproxy:
  forward: 127.0.0.1:9910
  server_addr: 127.0.0.1:9900
  register_route: 
  user:
    access_key: "xxxxxxxx"
    secret: "yyyyyyyyy"
pubproxy:
  server_addr: 0.0.0.0:9900
  input_addr: ":9920"
  user_map:
    "xxxxxxxx":
      access_key: "xxxxxxxx"
      secret: "yyyyyyyyy"
    "bcc":
      access_key: "bcc"
      secret: "sss2"
  